### ISSUE TITLE
Black screens

### ISSUE THREAD

**Issue by GE90115B** [markszutor/LVFR-A318-FBW-Compatibility-Mod#1]
Black screens even after turning on battery and EXT PWR. I have the FBW Experimental Version installed which could be conflicting possibly?

**Comment by markszutor** [comment]
This mod is not currently finished / finalised. FBW A32NX shouldn't conflict at all, neither should any other FBW mod (unless it is specifically relying on FBW to be installed) like karuchie's A319/A321neo mod

We have already confirmed no interference on our end with FBW Stable, Development or Experimental.

Also if possible, instead of opening a ticket here on GitHub, please join us on Discord as we can assist you there a lot easier.
